### ISSUE TITLE
brew cask apps aren't detected to be opened as an Application

### ISSUE THREAD

**Issue by agustifernandez** [lacona/lacona#10]
I am not able to find my brew cask installed apps with Lacona.

Here is the equivalent of this issue on brew cask's repo in relation to alfred [caskroom/homebrew-cask Installed apps can't be found by Alfred (issue #4327)](https://github.com/caskroom/homebrew-cask/issues/4327)

I guess an mvp of this would be some way to add path's to lacona's indexing scope, that way you don't solve the problem of apps installed via cask brew not showing up out of the box, but you potentially let others find out which path's they would include by default.

**Comment by brandonhorst** [comment]
Moving this to LaconaApp.

**Comment by brandonhorst** [comment]
This issue was moved to lacona/LaconaApp#23
