### ISSUE TITLE
Cannot read property 'defaultProps' of undefined

### ISSUE THREAD

**Issue by Chexpir** [lacona/lacona#8]
The Constructor is null hence it fails.

function getRealProps(_ref2) {
  var descriptor = _ref2.descriptor;
  var Constructor = _ref2.Constructor;

  var realProps = _lodash2['default'].defaults(descriptor.props || {}, Constructor.defaultProps || {}); //FAILING LINE
  if (descriptor.children && descriptor.children.length > 0) {
    realProps.children = _lodash2['default'].flattenDeep(descriptor.children);
  }
  return realProps;
}

**Comment by brandonhorst** [comment]
The issue with this is that you are setting an invalid Phrase Element as `parser.grammar`, or you are returning an invalid Phrase Element from `describe()` call.

Are you reporting the misleading error message, or are you having trouble with a grammar? I do want to add better error reporting across the board, especially this one.

**Comment by brandonhorst** [comment]
Fixed with https://github.com/lacona/lacona/commit/e223f7368788eebf4ab531465bb8a64211040815
